

    <script type="text/javascript">

        document.documentElement.className ="has-js " + document.documentElement.className;

        var url = document.URL;
        url = url.split('/');
        url.pop();
        url = url.join('/');
        var CONF = {};

        CONF.baseUrl = url;
        jQuery(document).ready(function () {
           jQuery('.breadcrumbs').hide();
        });
        // console.log(CONF.baseUrl);

    </script>

    <!-- CSS -->
    <link rel="stylesheet" href="/ulysses-event/css/app.css">
    


    <div id="event-page">

        <div id="container">

            <div id="top-frame">

                <div id="logo"></div>

                <div id="top-text">
                    <h2>Ulysses Tier 1</h2>
                    <h1>
                        LAUNCH <br />
                        EVENT 
                    </h1>
                </div>

                <img src="/ulysses-event/imgs/bag.png" id="bag">

                <img id="eye" src="/ulysses-event/imgs/eye.png">

                <div id="scroll-text" href="/ulysses1-event/"><span class="text">PHOTOS AND VIDEO BELOW</span><span class="arrow"></span></div>

            </div>


            <div id="content">
                <div class="content-wrapper">
                    
                    <div class="below-top">
                        <div class="kit-link">
                            <a href="/ulysses-lander/">Explore the kit</a>
                            <div id="link-arrow"></div>
                        </div>

                        <div class="header-text">
                            <h3>ULYSSES TIER 1</h3>
                            <h1>DISASTER RELIEF KIT</h1>
                            <h2>LAUNCH EVENT</h2>
                            <h3>DECEMBER 5 - LOS ANGELES</h3>
                            <h4>EVENT DESIGN BY BUREAU<span>BETAK</span></h4>
                        </div>

                        <div class="two-col clearfix">
                            <div class="col faded">
                                <p>We wanted people to be surprised. Our customers and friends have come to expect special things from Just One Eye and we did not want to disappoint. </p>

                                <p>Ulysses Tier 1 Disaster Relief Kit is our 2014-collaboration concept. We wanted to make sure that the kit came across in a special and impactful way. We decided to bring it to life through a motorized reveal, helicopters, the grand orchestra, the excitement of the dancers, the presentation of the food (with the concept of survival rations), which all came together with the great work of Bureau Betak. </p>
                            </div>
                            <div class="col">
                                <p>The platform for the orchestra, which was physically built by Bureau Betak with direction from Just One Eye, as well as the spot where the dancers could climb over the walls to surprise the guests – It’s as if the roof was made for the event!</p>

                            </div>
                        </div>



                        <div class="header-text first-video-text">

                            <h2>FILM PREVIEW</h2>

                        </div>

                        <div class='video'>
                            <iframe src="//player.vimeo.com/video/114270556" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                        </div>


                    </div>

                    <div class="filter-container clearfix">
                        <div id="filter-title"><span>FILTER PHOTOS</span></div>
                        <div class="buttons">
                            <div class="filter-button active all" data-filter="all"><span>ALL</span></div>
                            <div class="filter-button" data-filter="people"><span>PEOPLE</span></div>
                            <div class="filter-button" data-filter="event"><span>THE EVENT</span></div>
                            <div class="filter-button" data-filter="venue"><span>VENUE</span></div>
                        </div>
                    </div>


                    

                    <div class="three-col-grid clearfix">

                        <!-- PEOPLE -->

                        <div class="slideshow-container slideshow-one content-el" data-category="people">
                                                    <div class="button left-button"></div>
                                                    <div class="button right-button"></div>
                                                    <div class="slideshow-body">

                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/9.jpg" class="slideshow-img">
                                                        </div>

                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/23.jpg" class="slideshow-img">
                                                        </div>
                                                        
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/people/slideshow1400x800/1.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/people/slideshow1400x800/2.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/people/slideshow1400x800/3.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/people/slideshow1400x800/17.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/people/slideshow1400x800/25.jpg" class="slideshow-img">
                                                        </div>

                                                    </div>
                                                    
                        </div>
                        <div class="two-col-el cat-images-title content-el right-col" data-category="people">
                            <img class="one-col-item" src="/ulysses-event/imgs/people/716x400/716x400.jpg">
                            <div class="one-col-item caption"><span>Suddenly, a series of spotlight beams began cutting through the sky as a live orchestra back lit by eerily beautiful coloured lighting broke into the frantic opening bars of Wagner’s ‘Flight of the Valkyries’. </span></div>
                        </div>

                        <div class="one-col-el cat-images-grid right-col content-el" data-category="people">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/people/400x400/1.jpg">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/people/400x400/2.jpg">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/people/400x400/3.jpg">
                        </div>

                        <div class="one-col-el content-el cat-caption" data-category="people">
                            <div class="big-text">
                                <span class="bold">I was left reeling from the performance and on my way out,  in a slight daze…</span>
                                <span class="cursive">- Cher Coulter</span>
                            </div>
                        </div>

                        <div class="one-col-el cat-images-big content-el" data-category="people">
                            <img class="one-col-item" src="/ulysses-event/imgs/people/1100x600/1100x600.jpg">
                           
                            <div class="two-col-el right-col">
                                <div class="one-col-item caption"><span>Meanwhile, a group of dancers in black-face paint and skullcaps scaled the walls before swarming among clusters of unsuspecting guests to continue their military-influenced routine.</span></div>
                            </div>

                        </div>

                        <!-- EVENT -->

                        <div class="slideshow-container slideshow-two content-el" data-category="event">
                                                    <div class="button left-button"></div>
                                                    <div class="button right-button"></div>
                                                    <div class="slideshow-body">
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/1.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/2.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/3.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/7.jpg" class="slideshow-img">
                                                        </div>

                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/15.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/18.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/19.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/21.jpg" class="slideshow-img">
                                                        </div>

                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/event/slideshow_1400x800/26.jpg" class="slideshow-img">
                                                        </div>


                                                    </div>
                                                    
                        </div>
                        <div class="two-col-el cat-images-title content-el right-col" data-category="event">
                            <img class="one-col-item" src="/ulysses-event/imgs/event/716x400/716x400.jpg">
                            <div class="one-col-item caption"><span>A few minutes before 8 p.m., a purple light cast across the crowd and an orchestra marched in single file and positioned themselves along the roofline against the night sky. </span></div>
                        </div>

                        <div class="one-col-el cat-images-grid right-col content-el" data-category="event">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/event/400x400/400x400_1.jpg">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/event/400x400/400x400_2.jpg">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/event/400x400/400x400_3.jpg">
                        </div>

                        <div class="one-col-el content-el cat-caption" data-category="event">
                            <div class="big-text">
                                <span class="bold">This is a big event for me to show people the DNA of Just One Eye.<span>
                                <br /><span class="cursive">- Paola Russo</span>
                            </div>
                        </div>

                        <div class="one-col-el cat-images-big content-el" data-category="event">
                            <img class="one-col-item" src="/ulysses-event/imgs/event/1100x600/1100x600.jpg">
                           
                        </div>


                        <!-- VENUE -->

                        <div class="slideshow-container slideshow-three content-el" data-category="venue">
                                                    <div class="button left-button"></div>
                                                    <div class="button right-button"></div>
                                                    <div class="slideshow-body">
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/1.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/3.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/4.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/5.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/6.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/7.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/8.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/10.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/11.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/12.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/13.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/14.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/20.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/22.jpg" class="slideshow-img">
                                                        </div>
                                                        <div class="slideshow-item">
                                                            <img src="/ulysses-event/imgs/venue/slideshow_1400x800/24.jpg" class="slideshow-img">
                                                        </div>


                                                    </div>
                                                    
                        </div>
                        <div class="two-col-el cat-images-title content-el" data-category="venue">
                            <img class="one-col-item" src="/ulysses-event/imgs/venue/716x400/716x400.jpg">
                        </div>

                        <div class="one-col-el cat-images-grid right-col content-el" data-category="venue">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/venue/400x400/1.jpg">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/venue/400x400/2.jpg">
                            <img class="three-col-item col-img right-el" src="/ulysses-event/imgs/venue/400x400/3.jpg">
                        </div>

                        <div class="one-col-el content-el cat-caption" data-category="venue">
                            <div class="big-text">
                                <span class="bold">I didn’t want to<br /> miss the moment.</span>
                                <br /><span class="cursive">- Dita Von Teese.</span>
                            </div>
                        </div>

                        <div class="one-col-el cat-images-big content-el" data-category="venue">
                            <img class="one-col-item" src="/ulysses-event/imgs/venue/1100x600/1100x600.jpg">
                           

                        </div>



                    </div>
                    <div class="below-top">

                        <div class="header-text first-video-text">
                            <h3>ULYSSES TIER 1</h3>
                            <h1>DISASTER RELIEF KIT</h1>
                            <h2>EVENT FILM</h2>
                            <h3>DECEMBER 5 - LOS ANGELES</h3>
                        </div>

                        <div class='video'>
                            <iframe src="//player.vimeo.com/video/114272448" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>                        
                        </div> 

                        <div class="header-text first-video-text">

                            <h2>PRESS ARTICLES</h2>

                        </div>

                        <div class="articles">
                            <p> <a href="http://www.wwd.com/eye/parties/just-one-eye-hosts-cocktail-at-hollywood-boutique-8061922" target="_blank">WWD : Just One Eye Hosts Cocktail at Hollywood Boutique</a> </p>
                            <p> <a href="http://chercoulter.com/just-one-eye-survival-spectacular/" target="_blank">Cher coulter : Just One Eye’s Survival Spectacular</a> </p>
                            <p> <a href="http://www.coolhunting.com/design/ulysses-tier-1-disaster-relief-kit" target="_blank">Cool Hunting : Just One Eye's Ulysses Tier 1 Disaster Relief Kit</a> </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


 <script type="text/javascript" src="/ulysses-event/js/app.js"></script>

